[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphax"
version = "0.0.1"
description = "Graphax is an Automatic Differentiation interpreter written in JAX."
authors = [
    { name = "Jamie Lohoff", email = "jamie.lohoff@gmail.com" },
    { name = "Florian Assmuth", email = "florianassmuth@gmail.com" }
]
dynamic = ["urls"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE.txt" }
readme = "README.rst"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "jax>=0.5.0",
    "jaxlib>=0.5.0"
]

[tool.setuptools]
package-dir = {"" = "src"}
